---
# This playbook fills in the template iptables.j2 to create an iptables rules file with values 
# from "firewall_whitelist_ip_port" located in group_vars/all, the loads them into the active chain.
- hosts: all
  sudo: yes
  tasks:
  # RedHat family
  - name: ensure required packages are installed
    yum: name="libselinux-python" state=installed
    when: ansible_os_family == "RedHat"

  - name: copy firewall template
    template: src=iptables.j2 dest="/etc/sysconfig/iptables.rules.v4"
    when: ansible_os_family == "RedHat"

  - name: import firewall rules
    shell: "iptables-restore < /etc/sysconfig/iptables.rules.v4"
    when: ansible_os_family == "RedHat"

  # Debian family + other distros
  - name: copy firewall template
    template: src=iptables.j2 dest="/etc/iptables.rules.v4"

  - name: import firewall rules
    shell: "iptables-restore < /etc/iptables.rules.v4"